python ../wait.py
python ../train_nichecompass_reference_model.py \
--dataset spatial_atac_rna_seq_mouse_brain_batch2 \
--reference_batches None \
--n_neighbors 8 \
--filter_genes \
--n_hvg 3000 \
--nichenet_keep_target_genes_ratio 0.01 \
--nichenet_max_n_target_genes_per_gp 1000 \
--include_mebocost_gps \
--mebocost_species mouse \
--gp_filter_mode subset \
--combine_overlap_gps \
--overlap_thresh_source_genes 0.9 \
--overlap_thresh_target_genes 0.9 \
--overlap_thresh_genes 0.9 \
--counts_key counts \
--condition_key batch \
--spatial_key spatial \
--adj_key spatial_connectivities \
--mapping_entity_key mapping_entity \
--gp_targets_mask_key nichecompass_gp_targets \
--gp_sources_mask_key nichecompass_gp_sources \
--gp_names_key nichecompass_gp_names \
--include_atac_modality \
--filter_peaks \
--min_cell_peak_thresh_ratio 0.0005 \
--model_label one-hop-norm_reference \
--active_gp_names_key nichecompass_active_gp_names \
--latent_key nichecompass_latent \
--active_gp_thresh_ratio 0.01 \
--gene_expr_recon_dist nb \
--cond_embed_injection gene_expr_decoder chrom_access_decoder \
--n_cond_embed None \
--log_variational \
--node_label_method one-hop-norm \
--n_layers_encoder 1 \
--n_hidden_encoder None \
--conv_layer_encoder gcnconv \
--n_epochs 100 \
--n_epochs_all_gps 25 \
--n_epochs_no_cond_contrastive 0 \
--lr 0.001 \
--lambda_edge_recon 500000. \
--lambda_gene_expr_recon 300. \
--lambda_chrom_access_recon 100. \
--lambda_cond_contrastive 0. \
--contrastive_logits_ratio 0. \
--lambda_group_lasso 5. \
--lambda_l1_masked 30. \
--edge_batch_size 4096 \
--node_batch_size None
