python ../wait.py
python ../map_query_on_nichecompass_reference_model.py \
--dataset seqfish_mouse_organogenesis_imputed \
--query_batches batch5 batch6 \
--n_neighbors 12 \
--spatial_key spatial \
--mapping_entity_key mapping_entity \
--gp_names_key nichecompass_gp_names \
--reference_model_label one-hop-norm_reference \
--load_timestamp 23052023_162708 \
--query_model_label one-hop-norm_query \
--reference_query_model_label one-hop-norm_reference_query \
--n_epochs 1 \
--n_epochs_all_gps 25 \
--n_epochs_no_cond_contrastive 0 \
--lr 0.001 \
--lambda_edge_recon 500000. \
--lambda_gene_expr_recon 100. \
--lambda_cond_contrastive 0. \
--contrastive_logits_ratio 0. \
--lambda_group_lasso 0. \
--lambda_l1_masked 0. \
--edge_batch_size 4096 \
--node_batch_size None
