name: cellcharter
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - mamba
  - pip
  - python=3.10
  - optax=0.2.0
  - jaxlib=0.4.12=*cuda*
  - jax=0.4.12
  - pytorch
  - pytorch-cuda=11.7
  - scipy==1.12.0
  - scvi-tools=0.20.3
  - pip:
    - ipywidgets
    - jupyterlab
    - cellcharter
