name: stalign
channels:
  - pytorch
  - pyg
  - nvidia
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytorch=2.0.0
  - pytorch-scatter=2.1.1
  - pytorch-sparse=0.6.17
  - pytorch-cuda=11.7
  - bedtools=2.30.0
  - geckodriver=0.33.0
  - pip:
    - ipykernel==6.15.3
    - ipywidgets==8.0.2
    - jupyterlab==3.4.7
    - pynrrd==1.1.1